export type OnboardingStepTemplate = {
  title:                string;
  description:          string;
  category:             string;
  sortOrder:            number;
  blockedBySortOrder?:  number; // sortOrder of the prerequisite step
};

// ─── Employee Onboarding ──────────────────────────────────────────────────────
export const EMPLOYEE_ONBOARDING_STEPS: OnboardingStepTemplate[] = [
  { title: "Sign offer letter / employment agreement",          category: "LEGAL",    sortOrder: 1,
    description: "Confirm signed copy is on file before start date." },
  { title: "Sign NDA and confidentiality agreement",            category: "LEGAL",    sortOrder: 2,
    description: "Route through DocuSign or manual signature. Store signed copy in employee Documents.",
    blockedBySortOrder: 1 },
  { title: "Complete I-9 verification",                         category: "HR",       sortOrder: 3,
    description: "Verify employment eligibility documents. Upload copies to employee record.",
    blockedBySortOrder: 2 },
  { title: "Set up direct deposit / payroll",                   category: "HR",       sortOrder: 4,
    description: "Collect bank info via secure form. Submit to payroll by Friday of start week.",
    blockedBySortOrder: 3 },
  { title: "Send Employee Handbook for acknowledgement",        category: "HR",       sortOrder: 5,
    description: "Send via policy acknowledgement flow in WVW Intelligence. Track completion in the employee's policy tab.",
    blockedBySortOrder: 3 },
  { title: "Add employee to HR system and org chart",           category: "HR",       sortOrder: 6,
    description: "Create employee record in WVW Intelligence, assign department and manager.",
    blockedBySortOrder: 3 },
  { title: "Create email account and calendar",                 category: "IT",       sortOrder: 7,
    description: "Set up company email. Add to relevant team calendars and distribution lists.",
    blockedBySortOrder: 6 },
  { title: "Grant platform access (WVW Intelligence)",          category: "IT",       sortOrder: 8,
    description: "Invite via Clerk. Assign correct role. Confirm login works.",
    blockedBySortOrder: 7 },
  { title: "Share tool access and credentials",                 category: "IT",       sortOrder: 9,
    description: "Provide access to Slack, project tools, Notion, shared drives.",
    blockedBySortOrder: 8 },
  { title: "Set up laptop and required software",               category: "IT",       sortOrder: 10,
    description: "Configure machine. Confirm VPN, security settings, and backup.",
    blockedBySortOrder: 8 },
  { title: "Send welcome email with first-day details",         category: "HR",       sortOrder: 11,
    description: "Include start time, dress code, parking/entry instructions, and first-day agenda.",
    blockedBySortOrder: 10 },
  { title: "Assign onboarding buddy",                           category: "CULTURE",  sortOrder: 12,
    description: "Pair new hire with a peer buddy for informal questions and culture integration.",
    blockedBySortOrder: 11 },
  { title: "Schedule 1:1 with direct manager (Day 1)",          category: "CULTURE",  sortOrder: 13,
    description: "30-minute check-in to walk through first-week expectations and the 30/60/90 plan.",
    blockedBySortOrder: 11 },
  { title: "Assign mandatory onboarding training",              category: "TRAINING", sortOrder: 14,
    description: "Assign WVW Culture & Values training, DEI Foundations, and role-specific modules in the Academy.",
    blockedBySortOrder: 13 },
  { title: "Complete WVW Culture & Values orientation",         category: "TRAINING", sortOrder: 15,
    description: "60-minute live or async session covering WVW's mission, values, and culture practices.",
    blockedBySortOrder: 14 },
  { title: "Shadow first client engagement or audit",           category: "TRAINING", sortOrder: 16,
    description: "Arrange observation opportunity with a senior team member within the first 30 days.",
    blockedBySortOrder: 15 },
  { title: "Intro post in team community",                      category: "CULTURE",  sortOrder: 17,
    description: "Encourage new hire to post a brief intro in the team Announcements space.",
    blockedBySortOrder: 15 },
  { title: "30-day check-in meeting",                           category: "CULTURE",  sortOrder: 18,
    description: "Structured 1:1 to review onboarding progress, surface blockers, assess cultural fit.",
    blockedBySortOrder: 17 },
  { title: "60-day performance touchpoint",                     category: "CULTURE",  sortOrder: 19,
    description: "Review initial work product, set OKRs for next 30 days.",
    blockedBySortOrder: 18 },
  { title: "90-day review and confirmation",                    category: "CULTURE",  sortOrder: 20,
    description: "Formal 90-day review. Confirm role continuation, adjust title/level if needed.",
    blockedBySortOrder: 19 },
];

// ─── Employee Offboarding ─────────────────────────────────────────────────────
export const EMPLOYEE_OFFBOARDING_STEPS: OnboardingStepTemplate[] = [
  { title: "Confirm last day and final pay calculation",        category: "HR",       sortOrder: 1,
    description: "Verify last working day, calculate PTO payout, and confirm final paycheck date." },
  { title: "Send separation paperwork",                         category: "HR",       sortOrder: 2,
    description: "Provide COBRA notice, final paycheck info, and any severance documentation.",
    blockedBySortOrder: 1 },
  { title: "Conduct exit interview",                            category: "HR",       sortOrder: 3,
    description: "Schedule 30-minute exit interview. Document feedback and flag any retention insights.",
    blockedBySortOrder: 1 },
  { title: "Transition active client accounts",                 category: "GENERAL",  sortOrder: 4,
    description: "Assign all active client engagements, audits, and open tasks to a new owner.",
    blockedBySortOrder: 1 },
  { title: "Close or reassign open tasks and milestones",       category: "GENERAL",  sortOrder: 5,
    description: "Review all open tasks. Reassign to active team members or close with documentation.",
    blockedBySortOrder: 4 },
  { title: "Transfer files and knowledge",                      category: "IT",       sortOrder: 6,
    description: "Ensure all project files, client contacts, and institutional knowledge are transferred.",
    blockedBySortOrder: 4 },
  { title: "Revoke platform and system access",                 category: "IT",       sortOrder: 7,
    description: "Disable WVW Intelligence login, email, Slack, shared drives on last day.",
    blockedBySortOrder: 6 },
  { title: "Retrieve company equipment",                        category: "IT",       sortOrder: 8,
    description: "Arrange return of laptop, badge, and any other company property.",
    blockedBySortOrder: 7 },
  { title: "Forward email or set auto-reply",                   category: "IT",       sortOrder: 9,
    description: "Set up email forwarding or out-of-office for 30 days post-departure.",
    blockedBySortOrder: 7 },
  { title: "Update employee status to TERMINATED",              category: "HR",       sortOrder: 10,
    description: "Change employment status in workforce tracker.",
    blockedBySortOrder: 8 },
  { title: "Remove from org chart and payroll",                 category: "HR",       sortOrder: 11,
    description: "Update reporting structure. Remove from active payroll after final pay.",
    blockedBySortOrder: 10 },
  { title: "Post farewell announcement",                        category: "CULTURE",  sortOrder: 12,
    description: "Post in team Announcements.",
    blockedBySortOrder: 10 },
  { title: "Send farewell gift or card (if applicable)",        category: "CULTURE",  sortOrder: 13,
    description: "Coordinate team card or farewell gesture in alignment with WVW culture values.",
    blockedBySortOrder: 12 },
];

// ─── Client Onboarding ────────────────────────────────────────────────────────
export const CLIENT_ONBOARDING_STEPS: OnboardingStepTemplate[] = [
  { title: "Execute client services agreement",                 category: "LEGAL",    sortOrder: 1,
    description: "Send, collect signatures on, and file the master services agreement. No work begins until signed." },
  { title: "Execute NDA / confidentiality agreement",           category: "LEGAL",    sortOrder: 2,
    description: "Confirm NDA is signed by all relevant parties and stored in client Documents.",
    blockedBySortOrder: 1 },
  { title: "Create client record in WVW Intelligence",          category: "GENERAL",  sortOrder: 3,
    description: "Add full company profile: industry, size, billing info, primary contact, and health score baseline.",
    blockedBySortOrder: 2 },
  { title: "Assign account owner and team members",             category: "GENERAL",  sortOrder: 4,
    description: "Set the lead consultant and any supporting team members on the client record.",
    blockedBySortOrder: 3 },
  { title: "Set up billing and invoicing",                      category: "GENERAL",  sortOrder: 5,
    description: "Configure billing email, payment terms, and default rate.",
    blockedBySortOrder: 4 },
  { title: "Send welcome email and portal access",              category: "GENERAL",  sortOrder: 6,
    description: "Send the client welcome email with portal link and assigned consultant's contact info.",
    blockedBySortOrder: 5 },
  { title: "Conduct kickoff meeting",                           category: "GENERAL",  sortOrder: 7,
    description: "60-minute kickoff: review scope, timeline, deliverables, key contacts, and communication cadence.",
    blockedBySortOrder: 6 },
  { title: "Collect intake questionnaire / needs assessment",   category: "GENERAL",  sortOrder: 8,
    description: "Send and collect the WVW intake form covering organizational goals, pain points, and compliance needs.",
    blockedBySortOrder: 7 },
  { title: "Schedule initial audit or assessment",              category: "GENERAL",  sortOrder: 9,
    description: "Book the first formal audit or gap assessment based on intake findings.",
    blockedBySortOrder: 8 },
  { title: "Establish communication and reporting cadence",     category: "GENERAL",  sortOrder: 10,
    description: "Agree on meeting frequency, preferred channels, and reporting format.",
    blockedBySortOrder: 9 },
  { title: "30-day relationship check-in",                      category: "GENERAL",  sortOrder: 11,
    description: "Review early engagement satisfaction, address any friction, and confirm scope alignment.",
    blockedBySortOrder: 10 },
];

// ─── Student / Cohort Onboarding ──────────────────────────────────────────────
export const STUDENT_ONBOARDING_STEPS: OnboardingStepTemplate[] = [
  { title: "Confirm enrollment and collect registration info",  category: "GENERAL",  sortOrder: 1,
    description: "Verify full name, email, employer (if applicable), and payment status." },
  { title: "Collect signed program agreement / terms",          category: "LEGAL",    sortOrder: 2,
    description: "Obtain signed acknowledgement of program expectations, refund policy, and code of conduct.",
    blockedBySortOrder: 1 },
  { title: "Grant Academy / LMS access",                        category: "IT",       sortOrder: 3,
    description: "Create learner account and enroll in assigned cohort courses.",
    blockedBySortOrder: 2 },
  { title: "Send welcome and orientation materials",            category: "GENERAL",  sortOrder: 4,
    description: "Send the welcome packet: schedule, facilitator contacts, platform guide, and first assignment.",
    blockedBySortOrder: 3 },
  { title: "Complete platform orientation module",              category: "TRAINING", sortOrder: 5,
    description: "Student completes the Academy orientation module before accessing course content.",
    blockedBySortOrder: 4 },
  { title: "Assign cohort buddy or peer group",                 category: "CULTURE",  sortOrder: 6,
    description: "Pair student with a peer for accountability and community.",
    blockedBySortOrder: 5 },
  { title: "30-day progress check-in",                          category: "GENERAL",  sortOrder: 7,
    description: "Review course progress, engagement, and any barriers to completion.",
    blockedBySortOrder: 6 },
  { title: "Mid-program assessment",                            category: "TRAINING", sortOrder: 8,
    description: "Administer the mid-program quiz or practical assessment.",
    blockedBySortOrder: 7 },
  { title: "Final assessment / capstone submission",            category: "TRAINING", sortOrder: 9,
    description: "Student submits final project or completes final exam.",
    blockedBySortOrder: 8 },
  { title: "Issue credential / certificate of completion",      category: "GENERAL",  sortOrder: 10,
    description: "Generate and deliver WVW issued credential upon passing final assessment.",
    blockedBySortOrder: 9 },
];

// ─── Role change (no blocking — all tasks run in parallel) ────────────────────
export const ROLE_CHANGE_STEPS: OnboardingStepTemplate[] = [
  { title: "Update role in HR system and org chart",            category: "HR",       sortOrder: 1,
    description: "Update title, department, level, and reporting structure in WVW Intelligence." },
  { title: "Adjust system access and permissions",              category: "IT",       sortOrder: 2,
    description: "Review and update platform role, tool access, and shared folder permissions." },
  { title: "Brief team on new responsibilities",                category: "CULTURE",  sortOrder: 3,
    description: "Post announcement in community. Schedule intro with any new direct reports." },
  { title: "Assign role-specific training modules",             category: "TRAINING", sortOrder: 4,
    description: "Enroll in any Academy courses required for the new role." },
  { title: "30-day check-in on new role performance",           category: "CULTURE",  sortOrder: 5,
    description: "Structured conversation with manager reviewing transition, challenges, and early wins." },
];

// Backwards-compatible alias used by workforce route
export const NEW_HIRE_STEPS = EMPLOYEE_ONBOARDING_STEPS;
